### ISSUE TITLE
Issue with installer.sh 

### ISSUE THREAD

**Issue by nickian** [ddvk/rmfakecloud-proxy#10]
In the `installer.sh` script, I noticed this output on the last line:

`sed: -i requires an argument`

```
root@reMarkable:~# ./installer.sh install
Extracting embedded binary...
Failed to stop proxy.service: Unit proxy.service not loaded.
~/rmfakecloud ~
CA exists
Private key exists
Pub key exists
crt exists
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Enter your own cloud url [http(s)://somehost:port] >https://rm.mydomain.com
Setting cloud sync to: https://rm.mydomain.com
Created symlink /etc/systemd/system/multi-user.target.wants/proxy.service → /etc/systemd/system/proxy.service.
Patching /etc/hosts
Stoping xochitl..
Fixing sync status...
sed: -i requires an argument
```

This modification was suggested by ChatGPT. This didn't actually resolve [my issue with rmfakecloud not syncing that I mention here](https://github.com/ddvk/rmfakecloud/issues/276), but it did get rid of the `sed: -i requires an argument` warning in the output.

```bash
# marks all as unsynced so that they are not deleted
#function fixsync(){
#    grep sync ~/.local/share/remarkable/xochitl/*.metadata -l | xargs sed -i 's/synced\": true/synced\": false/'
#}
function fixsync() {
    for file in ~/.local/share/remarkable/xochitl/*.metadata; do
        if grep -q sync "$file"; then
            sed -i '' 's/synced\": true/synced\": false/' "$file"
        fi
    done
}
```

**Comment by Eeems** [comment]
#9 will fix this. ChatGPT's solution will work, but is very verbose compared to just using the `-r` flag for `xargs`.

**Comment by Eeems** [comment]
This should be fixed now that my PR is merged

**Comment by nickian** [comment]
I tried replacing the install.sh with the updated one, but I get this issue now when I try to use it for the install.

```
Getting the installer...
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: note: TLS certificate validation not implemented
saving to 'installer.sh'
installer.sh         100% |******************************************************************************************************************************************************************************************************************************************************|  5694  0:00:00 ETA
'installer.sh' saved
Running the installer...
Extracting embedded binary...
Failed to stop proxy.service: Unit proxy.service not loaded.
gunzip: invalid magic
```

**Comment by Eeems** [comment]
The source file doesn't contain the embedded binary, so you can't run it directly. @ddvk will need to trigger a new release on the rmfakecloud-proxy repository to generate the final script.

You can also manually create it by pulling down the repository to your machine and running `make all`. The resulting script will be `dist/installer.sh`

**Comment by nickian** [comment]
Oh ok, thank you. I did that and ran the installer without any errors. Did not fix my issue [here](https://github.com/ddvk/rmfakecloud/issues/276), but it must be a separate issue.

**Comment by Eeems** [comment]
@ddvk could you create a new tag before closing this issue?
