### ISSUE TITLE
wget: note: TLS certificate validation not implemented

### ISSUE THREAD

**Issue by xmeadow** [ddvk/rmfakecloud-proxy#11]
After running `sh -c "$(wget https://raw.githubusercontent.com/ddvk/rmfakecloud/master/scripts/device/automagic.sh -O-)"` on th device it returns the following:
```
Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |************************************************************************|   275  0:00:00 ETA
written to stdout
Getting the installer...
Connecting to github.com (140.82.121.3:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
```

Softwareversion on device: 3.9.3.1986

**Comment by Eeems** [comment]
Copy a statically compiled copy of wget to your device (https://github.com/toltec-dev/bootstrap/) and use that instead.

**Comment by xmeadow** [comment]
Thanks that worked like a charm!
Now the device stucks trying to log in. But this might be a issue for another day. =) Thanks!
