### ISSUE TITLE
Proxy service gets deleted on every reboot (Paper Pro)

### ISSUE THREAD

**Issue by jdk-21** [ddvk/rmfakecloud-proxy#12]
On the Paper Pro /etc seems to be mounted as an overlay filesystem, which means that the proxy service gets removed on every reboot and I don't know how to bypass this limitation. My first guess would be to use cron but that doesn't seems to be installed.
```
# mount | grep /etc
overlay on /etc type overlay (rw,relatime,lowerdir=/etc,upperdir=/var/volatile/etc,workdir=/var/volatile/.etc-work)
/dev/mapper/home-encrypted-disk on /etc/dropbear type ext4 (rw,relatime)
overlay on /mnt/lowerdir type overlay (rw,relatime,lowerdir=/etc,upperdir=/var/volatile/etc,workdir=/var/volatile/.etc-work)
```
https://github.com/ddvk/rmfakecloud/issues/322

**Comment by Eeems** [comment]
Have you tried unmounting the overlay and then making modifications?

**Comment by jdk-21** [comment]
Is unmounting /etc considered save? I don't want to brick the device.

**Comment by Eeems** [comment]
You are unmounting an overlay that resets all changes on boot so that you can modify the files it's masking.

You do risk making changes to it after that could cause problems. If you do end up causing problems, you could always go through recovery to get your device back to a working state.

**Comment by jdk-21** [comment]
I tried it with unmounting and it worked. This should be added to the docs. And that Paper Pro uses arm64.

**Comment by Eeems** [comment]
You can open a PR to add it.

**Comment by ddvk** [comment]
added the instructions to the readme

**Comment by 2Belette** [comment]
many thanks @ddvk
