### ISSUE TITLE
Supported reMarkable software versions & "roll back"

### ISSUE THREAD

**Issue by Aephir** [ddvk/rmfakecloud-proxy#7]
Hi,

First off, thanks or making this.

Before trying, I wanted to ask two things: 

1. Are there are any requirements/compatibility issues with any software version (e.g., like [Toltec](https://toltec-dev.org/) saying that using with anything newer than `2.15.1.1189` will brick the reMarkable device).
    - I didn't see any mention of this for `makecloud-proxy`, but I also did not see any mention of anything explicitly being compatible.
    - My reMarkable 2 shipped with software v3.0.5.56. 

3. Is there a guide/script to "roll back" (i.e., undo) what this script does? I didn't see any mention of this either.

**Comment by NotNotQuinn** [comment]
I just got this working under version 3.5. If you use the install.sh script you can do `./install.sh uninstall` and it should uninstall it.
